backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"

media_folder: content/assets
public_folder: /

collections:
  - name: "articles"
    label: "Article"
    folder: "content/articles"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Article Tag", name: "tag", widget: "string" }
      - { label: "Article Title", name: "title", widget: "string" }
      - { label: "Article Image", name: "image", widget: "image" }
      - {
          label: "Article Image Alternate Text",
          name: "imageAlt",
          widget: "string",
        }
      - { label: "Article Date", name: "date", widget: "datetime" }
      - { label: "Article Description", name: "description", widget: "string" }
      - { label: "Article Author", name: "author", widget: "string" }
      - { label: "Author Picture", name: "authorPic", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
